# Generated by Django 4.2.6 on 2024-08-20 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0002_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 47, 52, 352888)),
        ),
    ]
