# Generated by Django 4.2.6 on 2024-08-20 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0003_alter_gasto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 48, 50, 645394))),
            ],
        ),
        migrations.DeleteModel(
            name='gasto',
        ),
    ]
