# Generated by Django 4.2.6 on 2024-08-20 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0004_gast_delete_gasto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persona',
            new_name='Person',
        ),
        migrations.AlterField(
            model_name='gast',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 49, 3, 808307)),
        ),
    ]
