# Generated by Django 4.2.6 on 2024-08-20 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0005_rename_persona_person_alter_gast_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 49, 22, 628835))),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Persona',
        ),
        migrations.DeleteModel(
            name='Gast',
        ),
    ]
