# Generated by Django 4.2.6 on 2024-08-21 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0009_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='participantes',
            field=models.ManyToManyField(related_name='gastos_participados', to='gastosCompartidos.user'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 21, 30, 56, 82752)),
        ),
    ]
