# Generated by Django 4.2.6 on 2024-08-21 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('gastosCompartidos', '0012_rename_descripcion_gasto_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 2, 58, 31, 269163)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='participantes',
            field=models.ManyToManyField(related_name='gastos_participados', to='users.user'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pay_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to='users.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
