# Generated by Django 4.2.6 on 2024-08-21 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0013_alter_gasto_createdby_alter_gasto_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 3, 2, 15, 276104)),
        ),
    ]
