# Generated by Django 4.2.6 on 2024-08-21 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0015_rename_pay_by_gasto_pay_by_id_alter_gasto_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='acreedor_id',
            new_name='acreedor',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='debedor_id',
            new_name='debedor',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='pay_by_id',
            new_name='pay_by',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 3, 56, 21, 726006)),
        ),
    ]
