# Generated by Django 4.2.6 on 2024-08-21 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0016_rename_acreedor_id_deuda_acreedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 31, 40, 693087)),
        ),
    ]
