# Generated by Django 4.2.6 on 2024-08-21 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0018_alter_gasto_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='gasto_id',
            new_name='gasto',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 54, 27, 756093)),
        ),
    ]
