# Generated by Django 4.2.6 on 2024-08-21 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0019_rename_gasto_id_deuda_gasto_alter_gasto_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='acreedor',
            new_name='creditor',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='debedor',
            new_name='debtor',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='fecha_pago',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='monto',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 59, 1, 637191)),
        ),
    ]
