# Generated by Django 4.2.6 on 2024-08-21 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('gastosCompartidos', '0021_alter_deuda_state_alter_gasto_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Pagada'), ('D', 'Eliminada')], default='P', max_length=1)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debts_como_acreedor', to='users.user')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debts_como_debedor', to='users.user')),
            ],
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 5, 5, 30, 578328)),
        ),
        migrations.DeleteModel(
            name='Deuda',
        ),
        migrations.AddField(
            model_name='debt',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto', to='gastosCompartidos.gasto'),
        ),
    ]
