# Generated by Django 4.2.6 on 2024-08-21 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0022_debt_alter_gasto_date_delete_deuda_debt_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='fecha_creacion',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 5, 19, 20, 249173)),
        ),
    ]
