# Generated by Django 4.2.6 on 2024-08-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0023_rename_fecha_creacion_debt_date_alter_gasto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 5, 22, 5, 244331)),
        ),
    ]
