# Generated by Django 4.2.6 on 2024-08-21 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0025_rename_state_debt_status_alter_gasto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 6, 54, 30, 35291)),
        ),
    ]
