# Generated by Django 4.2.6 on 2024-08-22 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastosCompartidos', '0026_alter_gasto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 15, 52, 24, 687692)),
        ),
    ]
